// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Publish(ctx context.Context, key string, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockPublisher_Expecter) Publish(ctx interface{}, key interface{}, value interface{}) *MockPublisher_Publish_Call {
	return &MockPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, key, value)}
}

func (_c *MockPublisher_Publish_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPublisher_Publish_Call) Return(err error) *MockPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte) error) *MockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisherCloser creates a new instance of MockPublisherCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisherCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisherCloser {
	mock := &MockPublisherCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisherCloser is an autogenerated mock type for the PublisherCloser type
type MockPublisherCloser struct {
	mock.Mock
}

type MockPublisherCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisherCloser) EXPECT() *MockPublisherCloser_Expecter {
	return &MockPublisherCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPublisherCloser
func (_mock *MockPublisherCloser) Close() {
	_mock.Called()
	return
}

// MockPublisherCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPublisherCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPublisherCloser_Expecter) Close() *MockPublisherCloser_Close_Call {
	return &MockPublisherCloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPublisherCloser_Close_Call) Run(run func()) *MockPublisherCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPublisherCloser_Close_Call) Return() *MockPublisherCloser_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisherCloser_Close_Call) RunAndReturn(run func()) *MockPublisherCloser_Close_Call {
	_c.Run(run)
	return _c
}

// Publish provides a mock function for the type MockPublisherCloser
func (_mock *MockPublisherCloser) Publish(ctx context.Context, key string, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisherCloser_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisherCloser_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockPublisherCloser_Expecter) Publish(ctx interface{}, key interface{}, value interface{}) *MockPublisherCloser_Publish_Call {
	return &MockPublisherCloser_Publish_Call{Call: _e.mock.On("Publish", ctx, key, value)}
}

func (_c *MockPublisherCloser_Publish_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockPublisherCloser_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPublisherCloser_Publish_Call) Return(err error) *MockPublisherCloser_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisherCloser_Publish_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte) error) *MockPublisherCloser_Publish_Call {
	_c.Call.Return(run)
	return _c
}
