// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package encoder

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFFmpegRunner creates a new instance of MockFFmpegRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFFmpegRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFFmpegRunner {
	mock := &MockFFmpegRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFFmpegRunner is an autogenerated mock type for the FFmpegRunner type
type MockFFmpegRunner struct {
	mock.Mock
}

type MockFFmpegRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFFmpegRunner) EXPECT() *MockFFmpegRunner_Expecter {
	return &MockFFmpegRunner_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockFFmpegRunner
func (_mock *MockFFmpegRunner) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFFmpegRunner_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockFFmpegRunner_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFFmpegRunner_Expecter) Start(ctx interface{}) *MockFFmpegRunner_Start_Call {
	return &MockFFmpegRunner_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockFFmpegRunner_Start_Call) Run(run func(ctx context.Context)) *MockFFmpegRunner_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFFmpegRunner_Start_Call) Return(err error) *MockFFmpegRunner_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFFmpegRunner_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockFFmpegRunner_Start_Call {
	_c.Call.Return(run)
	return _c
}
